version: 2

jobs:
  unitTest:
    docker:
      - image: web3f/node:v0.1.0
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: |
            yarn test

  e2eTest:
    docker:
      - image: web3f/node-dind:v0.3.0
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn
      - run:
          name: Run tests
          command: |
            wget https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
            chmod a+x ./kind-linux-amd64
            mv ./kind-linux-amd64 /usr/local/bin/kind

            yarn e2e-test


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unitTest:
          filters:
            tags:
              only: /.*/
      - e2eTest:
          filters:
            tags:
              only: /.*/
