version: 2

jobs:
  lint:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout

      - run: yarn

      - run:
          name: Run tests
          command: |
            yarn test


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
