logLevel: 'info'
maximumExecutionTime: '60m'
mode: Local
size: 4
topology: Line
targetStd: 1.5
testCases:
- NumberOfPeers
dependencies:
  w3f/polkadot:
    image:
      repo: 'parity/polkadot'
      tag: 'v0.8.12'
    chart: 'v0.27.3'
