logLevel: 'info'
maximumExecutionTime: '60m'
mode: Local
size: 4
topology: Line
targetStd: 1.5
testCases:
- name: NumberOfPeers
  dependency:
    w3f/polkadot-lab-test-case-number-of-peers:
      version: "v0.1.0"
dependencies:
  w3f/polkadot:
    values:
      image:
        repo: 'parity/polkadot'
        tag: 'v0.8.12'
    version: 'v0.27.3'
